name: Build

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  flake-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check flake health
        uses: DeterminateSystems/flake-checker-action@v9

  build:
    runs-on: ubuntu-latest
    needs: flake-health-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Run Nix flake checks
        run: |
          nix flake check
      - name: Run Cargo tests
        working-directory: ./src-tauri
        run: nix develop -c cargo test
