name: Build

on:
  push:
    branches: [develop-firebase, main]
  pull_request:
    branches: [develop-firebase, main]
  workflow_dispatch:

jobs:
  flake-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Flake Health
        uses: DeterminateSystems/flake-checker-action@v9

  build:
    runs-on: ubuntu-latest
    needs: flake-health-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Run Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Run Nix Flake Checks
        run: |
          nix flake check
      - name: Install Dependencies
        run: |
          nix develop -c pnpm install
      - name: Run Unit Tests
        run: |
          nix develop -c pnpm run test:unit
      - name: Run Integration Tests
        run: |
          nix develop -c pnpm run test:integration