name: Deploy to Firebase Hosting on PR
on:
  workflow_run:
    workflows: ["Build"]
    types: 
      - completed

permissions:
  checks: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch != 'main' &&
      github.event.workflow_run.head_repository.full_name == github.repository
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARS_ANTIQUA }}
          projectId: ars-antiqua